### ISSUE TITLE
How do I show the current directory and Git branch in color?

### ISSUE THREAD

**Issue by bveeramani** [cdalvaro/github-vscode-theme-iterm#10]
In the screenshots, both the current directory (e.g, `/D/g/github-vscode-theme-iterm`) and branch (e.g., `upgrade/v5.0.0`) are shown in color. How do I do that?

**Comment by cdalvaro** [comment]
I use the [starship prompt](https://starship.rs) which has a lot of customizable plugins.

**Comment by bveeramani** [comment]
Okay, awesome. Thank you!

**Comment by cdalvaro** [comment]
This is my starship configuration if you want to see it: https://github.com/cdalvaro/dotfiles/blob/main/.config/starship.toml
