### ISSUE TITLE
Resources information in README file

### ISSUE THREAD

**Issue by vijayhardaha** [cdalvaro/github-vscode-theme-iterm#11]
When you have free time please update these informations:

- Please add which shell & additional tools did you use in the screenshots.
- If you're using ZSH/OMZ then please add the theme name.
- Any other plugin requires to get a similar view as the screenshot?

Side Question: I tried with `spaceship` zsh theme and some other theme as well but the current directory path is showing `CYAN` colour instead of `BLUE`
Not sure

**Comment by cdalvaro** [comment]
Hi!

Thank you for your request!

I have just updated the README file with some information [about my shell setup](https://github.com/cdalvaro/github-vscode-theme-iterm#about-my-shell-setup).

I hope it'll help you to customizing your shell as you like it!

Please, let me know if you still having questions about my config!

**Comment by vijayhardaha** [comment]
Thanks for the update. Appreciate it.
