### ISSUE TITLE
[BUG]: Colours don't match the sample image

### ISSUE THREAD

**Issue by oresttokovenko** [cdalvaro/github-vscode-theme-iterm#14]
### Description of the bug

<img width="1388" alt="Screenshot 2023-10-14 at 10 13 57" src="https://github.com/cdalvaro/github-vscode-theme-iterm/assets/51058259/49d1f8da-d205-48dd-a662-892b0661eb67">

-------

I've attempted to apply the "GitHub Dark Dimmed" theme as shown in the attached image. However, the syntax highlighting in my terminal doesn't match the examples you've provided on your repo page. I'm using the same theme in VS Code and it clearly doesn't match. Could you advise if I might be missing a step or if there's a configuration issue?

### Steps To Reproduce

1. Download the Github Dark Dimmed colour theme
2. Select it, and open a file in iTerm2
3. Compare it to the VS Code Github Dark Dimmed theme

**Comment by cdalvaro** [comment]
Hi!

I think your issue is not with the theme for iTerm but with vim.

You should try changing you vim theme to one that matches the GitHub color scheme. Try one of these ones:

* vim: https://github.com/cormacrelf/vim-colors-github
* nvim: https://github.com/projekt0n/github-nvim-theme

**Comment by oresttokovenko** [comment]
> Hi!
> 
> I think your issue is not with the theme for iTerm but with vim.
> 
> You should try changing you vim theme to one that matches the GitHub color scheme. Try one of these ones:
> 
> * vim: https://github.com/cormacrelf/vim-colors-github
> * nvim: https://github.com/projekt0n/github-nvim-theme

It seems that you're right, and it gets quite complicating just trying to match the colours. Thank you for your help!
