### ISSUE TITLE
[FEAT]: Hello, how did you implement the ⌘ symbol in your prompt? 

### ISSUE THREAD

**Issue by loserc6** [cdalvaro/github-vscode-theme-iterm#18]
### Description

When I use the character setting, it shows very small.

**Comment by cdalvaro** [comment]
I'm using the SF Symbol: "􀆔" (it's inside the quotes)

You can get the SF Symbols app from https://developer.apple.com/sf-symbols/, search for the symbol: `command`, and copy the symbol with <kbd>CMD</kbd> + <kbd>C</kbd>.

Then paste the symbol in your prompt config.

**Comment by loserc6** [comment]
Resolved, thank you!
