### ISSUE TITLE
How can I make the same colours for directories and cetera as shown on your picture?

### ISSUE THREAD

**Issue by pekhota** [cdalvaro/github-vscode-theme-iterm#8]
For ex this picture https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/images/GitHubThemeiTerm.png .
How can I make the same output?

**Comment by cdalvaro** [comment]
I use https://github.com/ogham/exa for listing directories and files. It's a great tool!

You can install it directly with Homebrew: `brew install exa`

```sh
exa --long --header --group --git --modified --color-scale
```

**Comment by pekhota** [comment]
Great! Thank you so much!
